version: "3.9"
volumes:
  StoreDbData:
services:
  database:
    image: "postgres:14beta2-buster"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: sepehrCRM
      POSTGRES_PASSWORD: 0024572926Sepehr@
      PGPASSWORD: 0024572926Sepehr@
      POSTGRES_DB: maktabCRM
      PGDATA: /db_data
    volumes:
      - StoreDbData:/db_data

